/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WhatIsAGameSlamIndexRouteImport } from './routes/what-is-a-game-slam/index'
import { Route as SlamsIndexRouteImport } from './routes/slams/index'
import { Route as SignUpIndexRouteImport } from './routes/sign-up/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ArtistsIndexRouteImport } from './routes/artists/index'
import { Route as UserProfileUserNameRouteImport } from './routes/_user-profile/$userName'
import { Route as SlamsCreateIndexRouteImport } from './routes/slams/create/index'
import { Route as ArtistsArtistNameIndexRouteImport } from './routes/artists/$artistName/index'
import { Route as SlamsShowIdRouteImport } from './routes/slams/show/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatIsAGameSlamIndexRoute = WhatIsAGameSlamIndexRouteImport.update({
  id: '/what-is-a-game-slam/',
  path: '/what-is-a-game-slam/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlamsIndexRoute = SlamsIndexRouteImport.update({
  id: '/slams/',
  path: '/slams/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpIndexRoute = SignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsIndexRoute = ArtistsIndexRouteImport.update({
  id: '/artists/',
  path: '/artists/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserProfileUserNameRoute = UserProfileUserNameRouteImport.update({
  id: '/_user-profile/$userName',
  path: '/$userName',
  getParentRoute: () => rootRouteImport,
} as any)
const SlamsCreateIndexRoute = SlamsCreateIndexRouteImport.update({
  id: '/slams/create/',
  path: '/slams/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsArtistNameIndexRoute = ArtistsArtistNameIndexRouteImport.update({
  id: '/artists/$artistName/',
  path: '/artists/$artistName/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlamsShowIdRoute = SlamsShowIdRouteImport.update({
  id: '/slams/show/$id',
  path: '/slams/show/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$userName': typeof UserProfileUserNameRoute
  '/artists': typeof ArtistsIndexRoute
  '/login': typeof LoginIndexRoute
  '/sign-up': typeof SignUpIndexRoute
  '/slams': typeof SlamsIndexRoute
  '/what-is-a-game-slam': typeof WhatIsAGameSlamIndexRoute
  '/slams/show/$id': typeof SlamsShowIdRoute
  '/artists/$artistName': typeof ArtistsArtistNameIndexRoute
  '/slams/create': typeof SlamsCreateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$userName': typeof UserProfileUserNameRoute
  '/artists': typeof ArtistsIndexRoute
  '/login': typeof LoginIndexRoute
  '/sign-up': typeof SignUpIndexRoute
  '/slams': typeof SlamsIndexRoute
  '/what-is-a-game-slam': typeof WhatIsAGameSlamIndexRoute
  '/slams/show/$id': typeof SlamsShowIdRoute
  '/artists/$artistName': typeof ArtistsArtistNameIndexRoute
  '/slams/create': typeof SlamsCreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_user-profile/$userName': typeof UserProfileUserNameRoute
  '/artists/': typeof ArtistsIndexRoute
  '/login/': typeof LoginIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
  '/slams/': typeof SlamsIndexRoute
  '/what-is-a-game-slam/': typeof WhatIsAGameSlamIndexRoute
  '/slams/show/$id': typeof SlamsShowIdRoute
  '/artists/$artistName/': typeof ArtistsArtistNameIndexRoute
  '/slams/create/': typeof SlamsCreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$userName'
    | '/artists'
    | '/login'
    | '/sign-up'
    | '/slams'
    | '/what-is-a-game-slam'
    | '/slams/show/$id'
    | '/artists/$artistName'
    | '/slams/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$userName'
    | '/artists'
    | '/login'
    | '/sign-up'
    | '/slams'
    | '/what-is-a-game-slam'
    | '/slams/show/$id'
    | '/artists/$artistName'
    | '/slams/create'
  id:
    | '__root__'
    | '/'
    | '/_user-profile/$userName'
    | '/artists/'
    | '/login/'
    | '/sign-up/'
    | '/slams/'
    | '/what-is-a-game-slam/'
    | '/slams/show/$id'
    | '/artists/$artistName/'
    | '/slams/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UserProfileUserNameRoute: typeof UserProfileUserNameRoute
  ArtistsIndexRoute: typeof ArtistsIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  SignUpIndexRoute: typeof SignUpIndexRoute
  SlamsIndexRoute: typeof SlamsIndexRoute
  WhatIsAGameSlamIndexRoute: typeof WhatIsAGameSlamIndexRoute
  SlamsShowIdRoute: typeof SlamsShowIdRoute
  ArtistsArtistNameIndexRoute: typeof ArtistsArtistNameIndexRoute
  SlamsCreateIndexRoute: typeof SlamsCreateIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-is-a-game-slam/': {
      id: '/what-is-a-game-slam/'
      path: '/what-is-a-game-slam'
      fullPath: '/what-is-a-game-slam'
      preLoaderRoute: typeof WhatIsAGameSlamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slams/': {
      id: '/slams/'
      path: '/slams'
      fullPath: '/slams'
      preLoaderRoute: typeof SlamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/': {
      id: '/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/': {
      id: '/artists/'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user-profile/$userName': {
      id: '/_user-profile/$userName'
      path: '/$userName'
      fullPath: '/$userName'
      preLoaderRoute: typeof UserProfileUserNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slams/create/': {
      id: '/slams/create/'
      path: '/slams/create'
      fullPath: '/slams/create'
      preLoaderRoute: typeof SlamsCreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/$artistName/': {
      id: '/artists/$artistName/'
      path: '/artists/$artistName'
      fullPath: '/artists/$artistName'
      preLoaderRoute: typeof ArtistsArtistNameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slams/show/$id': {
      id: '/slams/show/$id'
      path: '/slams/show/$id'
      fullPath: '/slams/show/$id'
      preLoaderRoute: typeof SlamsShowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UserProfileUserNameRoute: UserProfileUserNameRoute,
  ArtistsIndexRoute: ArtistsIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  SignUpIndexRoute: SignUpIndexRoute,
  SlamsIndexRoute: SlamsIndexRoute,
  WhatIsAGameSlamIndexRoute: WhatIsAGameSlamIndexRoute,
  SlamsShowIdRoute: SlamsShowIdRoute,
  ArtistsArtistNameIndexRoute: ArtistsArtistNameIndexRoute,
  SlamsCreateIndexRoute: SlamsCreateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
