/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WhatIsAGameSlamIndexRouteImport } from './routes/what-is-a-game-slam/index'
import { Route as WelcomeIndexRouteImport } from './routes/welcome/index'
import { Route as SlamsIndexRouteImport } from './routes/slams/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as HealthIndexRouteImport } from './routes/health/index'
import { Route as ArtistsIndexRouteImport } from './routes/artists/index'
import { Route as SlamsCreateIndexRouteImport } from './routes/slams/create/index'
import { Route as ArtistsArtistNameIndexRouteImport } from './routes/artists/$artistName/index'
import { Route as UserProfileUserNameIndexRouteImport } from './routes/_user-profile/$userName/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as SlamsShowIdIndexRouteImport } from './routes/slams/show/$id/index'
import { Route as AuthItchCallbackIndexRouteImport } from './routes/auth/itch/callback/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatIsAGameSlamIndexRoute = WhatIsAGameSlamIndexRouteImport.update({
  id: '/what-is-a-game-slam/',
  path: '/what-is-a-game-slam/',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeIndexRoute = WelcomeIndexRouteImport.update({
  id: '/welcome/',
  path: '/welcome/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlamsIndexRoute = SlamsIndexRouteImport.update({
  id: '/slams/',
  path: '/slams/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthIndexRoute = HealthIndexRouteImport.update({
  id: '/health/',
  path: '/health/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsIndexRoute = ArtistsIndexRouteImport.update({
  id: '/artists/',
  path: '/artists/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlamsCreateIndexRoute = SlamsCreateIndexRouteImport.update({
  id: '/slams/create/',
  path: '/slams/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsArtistNameIndexRoute = ArtistsArtistNameIndexRouteImport.update({
  id: '/artists/$artistName/',
  path: '/artists/$artistName/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserProfileUserNameIndexRoute =
  UserProfileUserNameIndexRouteImport.update({
    id: '/_user-profile/$userName/',
    path: '/$userName/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SlamsShowIdIndexRoute = SlamsShowIdIndexRouteImport.update({
  id: '/slams/show/$id/',
  path: '/slams/show/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthItchCallbackIndexRoute = AuthItchCallbackIndexRouteImport.update({
  id: '/auth/itch/callback/',
  path: '/auth/itch/callback/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artists': typeof ArtistsIndexRoute
  '/health': typeof HealthIndexRoute
  '/login': typeof LoginIndexRoute
  '/slams': typeof SlamsIndexRoute
  '/welcome': typeof WelcomeIndexRoute
  '/what-is-a-game-slam': typeof WhatIsAGameSlamIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$userName': typeof UserProfileUserNameIndexRoute
  '/artists/$artistName': typeof ArtistsArtistNameIndexRoute
  '/slams/create': typeof SlamsCreateIndexRoute
  '/auth/itch/callback': typeof AuthItchCallbackIndexRoute
  '/slams/show/$id': typeof SlamsShowIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artists': typeof ArtistsIndexRoute
  '/health': typeof HealthIndexRoute
  '/login': typeof LoginIndexRoute
  '/slams': typeof SlamsIndexRoute
  '/welcome': typeof WelcomeIndexRoute
  '/what-is-a-game-slam': typeof WhatIsAGameSlamIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$userName': typeof UserProfileUserNameIndexRoute
  '/artists/$artistName': typeof ArtistsArtistNameIndexRoute
  '/slams/create': typeof SlamsCreateIndexRoute
  '/auth/itch/callback': typeof AuthItchCallbackIndexRoute
  '/slams/show/$id': typeof SlamsShowIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artists/': typeof ArtistsIndexRoute
  '/health/': typeof HealthIndexRoute
  '/login/': typeof LoginIndexRoute
  '/slams/': typeof SlamsIndexRoute
  '/welcome/': typeof WelcomeIndexRoute
  '/what-is-a-game-slam/': typeof WhatIsAGameSlamIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_user-profile/$userName/': typeof UserProfileUserNameIndexRoute
  '/artists/$artistName/': typeof ArtistsArtistNameIndexRoute
  '/slams/create/': typeof SlamsCreateIndexRoute
  '/auth/itch/callback/': typeof AuthItchCallbackIndexRoute
  '/slams/show/$id/': typeof SlamsShowIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artists'
    | '/health'
    | '/login'
    | '/slams'
    | '/welcome'
    | '/what-is-a-game-slam'
    | '/api/auth/$'
    | '/$userName'
    | '/artists/$artistName'
    | '/slams/create'
    | '/auth/itch/callback'
    | '/slams/show/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artists'
    | '/health'
    | '/login'
    | '/slams'
    | '/welcome'
    | '/what-is-a-game-slam'
    | '/api/auth/$'
    | '/$userName'
    | '/artists/$artistName'
    | '/slams/create'
    | '/auth/itch/callback'
    | '/slams/show/$id'
  id:
    | '__root__'
    | '/'
    | '/artists/'
    | '/health/'
    | '/login/'
    | '/slams/'
    | '/welcome/'
    | '/what-is-a-game-slam/'
    | '/api/auth/$'
    | '/_user-profile/$userName/'
    | '/artists/$artistName/'
    | '/slams/create/'
    | '/auth/itch/callback/'
    | '/slams/show/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtistsIndexRoute: typeof ArtistsIndexRoute
  HealthIndexRoute: typeof HealthIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  SlamsIndexRoute: typeof SlamsIndexRoute
  WelcomeIndexRoute: typeof WelcomeIndexRoute
  WhatIsAGameSlamIndexRoute: typeof WhatIsAGameSlamIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  UserProfileUserNameIndexRoute: typeof UserProfileUserNameIndexRoute
  ArtistsArtistNameIndexRoute: typeof ArtistsArtistNameIndexRoute
  SlamsCreateIndexRoute: typeof SlamsCreateIndexRoute
  AuthItchCallbackIndexRoute: typeof AuthItchCallbackIndexRoute
  SlamsShowIdIndexRoute: typeof SlamsShowIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-is-a-game-slam/': {
      id: '/what-is-a-game-slam/'
      path: '/what-is-a-game-slam'
      fullPath: '/what-is-a-game-slam'
      preLoaderRoute: typeof WhatIsAGameSlamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome/': {
      id: '/welcome/'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slams/': {
      id: '/slams/'
      path: '/slams'
      fullPath: '/slams'
      preLoaderRoute: typeof SlamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/': {
      id: '/health/'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/': {
      id: '/artists/'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slams/create/': {
      id: '/slams/create/'
      path: '/slams/create'
      fullPath: '/slams/create'
      preLoaderRoute: typeof SlamsCreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/$artistName/': {
      id: '/artists/$artistName/'
      path: '/artists/$artistName'
      fullPath: '/artists/$artistName'
      preLoaderRoute: typeof ArtistsArtistNameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user-profile/$userName/': {
      id: '/_user-profile/$userName/'
      path: '/$userName'
      fullPath: '/$userName'
      preLoaderRoute: typeof UserProfileUserNameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slams/show/$id/': {
      id: '/slams/show/$id/'
      path: '/slams/show/$id'
      fullPath: '/slams/show/$id'
      preLoaderRoute: typeof SlamsShowIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/itch/callback/': {
      id: '/auth/itch/callback/'
      path: '/auth/itch/callback'
      fullPath: '/auth/itch/callback'
      preLoaderRoute: typeof AuthItchCallbackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtistsIndexRoute: ArtistsIndexRoute,
  HealthIndexRoute: HealthIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  SlamsIndexRoute: SlamsIndexRoute,
  WelcomeIndexRoute: WelcomeIndexRoute,
  WhatIsAGameSlamIndexRoute: WhatIsAGameSlamIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  UserProfileUserNameIndexRoute: UserProfileUserNameIndexRoute,
  ArtistsArtistNameIndexRoute: ArtistsArtistNameIndexRoute,
  SlamsCreateIndexRoute: SlamsCreateIndexRoute,
  AuthItchCallbackIndexRoute: AuthItchCallbackIndexRoute,
  SlamsShowIdIndexRoute: SlamsShowIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
